### ISSUE TITLE
[BUG] Token Elevation Carrying Over to New Token

### ISSUE THREAD

**Issue by msprijatelj** [erithtotl/wall-height#33]
Foundry Version 9 - Build 238
System tested: LANCER v1.0.3

The elevation used to calculate whether a token can see over a wall is not currently being updated upon selecting a new token.

Steps to reproduce:
1. Create 2 tokens (Token 1 and Token 2) and a wall of height 1 within a scene with line of sight enabled.
2. Select both tokens individually, and observe that neither of them can see over the wall.
3. Set Token 1's elevation equal to the wall's height.  Observe that Token 1 can see over the wall.
4. Select Token 2.  Observe that Token 2 can *also* see over the wall, despite having an elevation of 0.
5. Move Token 2.  Observe that Token 2 can no longer see over the wall after updating its position.

Expected behavior:
Wall Height uses the elevation (and height, when enabled) of the selected token to calculate wall vision upon selection of that token.

**Comment by erithtotl** [comment]
Will investigate, thanks
