### ISSUE TITLE
Foundry V9 - The attempted Token movementcollides with at least one Wall

### ISSUE THREAD

**Issue by JBerkvens** [erithtotl/wall-height#38]
I have a problem where the walls seemed to be working correctly in terms of vision, but when I try to move with the arrow keys it doesn't move and with dragging and dropping I get this message: "The attempted Token movementcollides with at least one Wall".

Wall Config (Top: 10, Bottom: 0)
![image](https://user-images.githubusercontent.com/6276155/147766542-98773996-db21-432b-8201-686a4e376f54.png)

Player View at 5 ft. Vision is blocked as I would expect
![image](https://user-images.githubusercontent.com/6276155/147766625-fb5c165a-b54f-4948-ad96-4933417e3682.png)

Player View at 15 ft. Vision is not blocked anymore (the token is above the wall)
![image](https://user-images.githubusercontent.com/6276155/147766598-57d2bd61-3311-4c46-8072-866fd1d26b5d.png)

Player View at 15 ft. After trying to drag and drop.
![image](https://user-images.githubusercontent.com/6276155/147766653-f19a17fd-ef53-4752-9050-3a8d2b8f9174.png)

The console does not show any output on the drag and drop.
This is with all other modules disabled except for:
- libWrapper (v1.11.0.1)
- socketlib (v1.0.10)
- Tidy UI - Game Settings (v0.1.28)
- Wall Height (v3.6.0.1)

**Comment by sangdrax8** [comment]
I was just checking because I am running 3.6 and am seeing a similar thing.  Vision seems to work, but movement is blocked.

**Comment by JBerkvens** [comment]
Hello, I've installed the new version (v3.6.0.2), but it still doesn't work. I'm going to take a look at the code that was changed in the Merge Request, if I get something working I'll try to create a new MR.
